### ISSUE TITLE
Build.xml fail

### ISSUE THREAD

**Issue by xllora** [rossjones/JFluidDB#1]
Just checked out the code and build it from scratch and the ant build failed. It is missing to include the classpath for the thirdparty dir. I am pasting below a diff for that file that works for me. 

Best,
X.

$ git diff build.xml 
diff --git a/build.xml b/build.xml
index d05d28f..fc3e471 100644
--- a/build.xml
+++ b/build.xml
@@ -6,6 +6,10 @@
   <property name="build" location="build"/>
   <property name="dist"  location="dist"/>
-  <path id="jfluiddb.classpath">
-        <fileset dir="thirdparty/" includes="*.jar"/>
-  </path>
  +
  <target name="init">
   
   <tstamp/>
  @@ -15,13 +19,13 @@
  
  <target name="compile" depends="init"
       description="compile the source " >
-    <javac srcdir="${src}" destdir="${build}"/>
-    <javac srcdir="${src}" destdir="${build}" classpathref="jfluiddb.classpath"/>
  </target>
  
  <target name="test" depends="compile"
       description="compile the source and the tests " >
  
  
-    <javac srcdir="${src}" destdir="${build}"/>
-    <javac srcdir="${src}" destdir="${build}"  classpathref="jfluiddb.classpath"/>
  
   </target>

@@ -38,4 +42,4 @@
     <delete dir="${build}"/>
     <delete dir="${dist}"/>
   </target>
-</project>
\ No newline at end of file
+</project>

**Comment by ntoll** [comment]
Hi Xllora,

Thanks for the diff ;-)

Quite independently of you, I removed the build.xml file yesterday evening so that others can choose their own build mechanism... (I also removed the /thirdparty dir and json.org code). My intention being to keep the repos _as simple as possible_ - i.e. just the source code under the com.fluidinfo namespace.

I'm a Java newbie (this is the first Java code I've written - but I have lots of .NET and Python experience though), so if Java is your strength then I'd welcome feedback, comments and ideas about how to make the lib more idiomatic and easy for users in the Java world.

How do Java devs organise the source for a library..? Would they be expecting a build.xml file..? As Java doesn't have the concept of a GAC/distutils how do I indicate the dependencies on jUnit and json.org..?

All the best,

Nicholas.
